[package]
name = "duraplot"
version = "0.1.0"
authors = ["fpg2012 <fpg2012@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.0"
sdl2 = "0.31.0"